GoogleCloudPlatform/policy-library

cloudbuild.yaml
cloudbuild/Dockerfile

It just runs "make test" for now.
See https://github.com/t12g/policy-library/pull/2/checks?check_run_id=99625649 for test run output.

Add cloudbuild support

---

Makefile
cloudbuild/Dockerfile

Also add curl installation in the Dockerfile. It was accidentally taken out in the previous PR.

Add make target for building and pushing Cloud Build Docker image

---

policies/templates/gcp_always_violates.yaml
validator/always_violates.rego
validator/always_violates_test.rego
validator/test/fixtures/constraints/always_violates_all/data.yaml

As discussed, we'll start with v1. If this looks good, I'll apply the change to other constraint templates in a follow-up PR.
Also remove the following fields:
* "listKind", since it defaults to <kind>List
* "constraintVersion", since version it's now part of constraint template name

Add version information as constraint template name suffix

---

policies/templates/gcp_always_violates.yaml
policies/templates/gcp_external_ip_access.yaml
policies/templates/gcp_iam_allowed_policy_member_domains.yaml
policies/templates/gcp_network_routing.yaml
policies/templates/gcp_storage_logging.yaml
samples/always_violates.yaml
samples/iam_service_accounts_only.yaml
validator/iam_allowed_policy_member_domains.rego
validator/iam_allowed_policy_member_domains_test.rego
validator/network_routing.rego
validator/network_routing_test.rego
validator/storage_logging.rego
validator/storage_logging_test.rego
validator/test/fixtures/constraints/forbid_external_ip_blacklist/data.yaml
validator/test/fixtures/constraints/forbid_external_ip_blacklist_all/data.yaml
validator/test/fixtures/constraints/forbid_external_ip_default/data.yaml
validator/test/fixtures/constraints/forbid_external_ip_whitelist/data.yaml
validator/test/fixtures/constraints/forbid_external_ip_whitelist_all/data.yaml
validator/test/fixtures/constraints/iam_allowed_policy_member_all_domains/data.yaml
validator/test/fixtures/constraints/iam_allowed_policy_member_reject_project_reference/data.yaml
validator/test/fixtures/constraints/iam_allowed_policy_member_two_domains/data.yaml
validator/test/fixtures/constraints/network_routing/data.yaml
validator/test/fixtures/constraints/require_storage_logging/data.yaml
validator/vm_external_ip.rego
validator/vm_external_ip_test.rego

Follow up to https://github.com/forseti-security/policy-library/pull/19
Also remove redundant listKind field in constraint templates.

Append "V1" version suffix to constraint template name

---

policies/templates/gcp_iam_allowed_bindings.yaml
samples/iam_blacklist_public.yaml
samples/iam_blacklist_role.yaml
samples/iam_restrict_role.yaml
validator/iam_allowed_bindings.rego
validator/iam_allowed_bindings_test.rego
validator/test/fixtures/assets/projects_iam/data.json
validator/test/fixtures/assets/projects_iam_bindings/data.json
validator/test/fixtures/constraints/iam_allowed_bindings_blacklist_public/data.yaml
validator/test/fixtures/constraints/iam_allowed_bindings_blacklist_role/data.yaml
validator/test/fixtures/constraints/iam_allowed_bindings_whitelist_role_domain/data.yaml
validator/test/fixtures/constraints/iam_allowed_bindings_whitelist_role_members/data.yaml

This constraint provides feature parity with the [existing Forseti IAM rules](https://github.com/forseti-security/forseti-security/blob/master/rules/iam_rules.yaml).
Fixes #21.

Add constraint to restrict IAM bindings

---

docs/constraint_template_authoring.md
docs/user_guide.md

Also add TOC. Original issue: https://github.com/forseti-security/config-validator/issues/21

Split template authoring section into its own page

---

policies/templates/gcp_cmek_rotation_v1.yaml
policies/templates/gcp_glb_external_ip_access_constraint_v1.yaml
policies/templates/gcp_sql_public_ip_v1.yaml

The position of the INLINE directive comment was causing the following errors:
```
ERROR: logging before flag.Parse: I0523 14:04:47.741779   17479 validator.go:116] Unable to convert file config-validator/release/policy-library/policies/templates/gcp_cmek_rotation_v1.yaml, with error unmarshal []byte to yaml failed: yaml: line 46: did not find expected key, assuming this file should be skipped and continuing
ERROR: logging before flag.Parse: I0523 14:04:47.742214   17479 validator.go:116] Unable to convert file config-validator/release/policy-library/policies/templates/gcp_glb_external_ip_access_constraint_v1.yaml, with error unmarshal []byte to yaml failed: yaml: line 55: did not find expected key, assuming this file should be skipped and continuing
ERROR: logging before flag.Parse: …
```

Fix indentation on template .yaml files

---

policies/templates/gcp_always_violates_v1.yaml
policies/templates/gcp_bq_dataset_location_v1.yaml
policies/templates/gcp_cmek_rotation_v1.yaml
policies/templates/gcp_compute_zone_v1.yaml
policies/templates/gcp_dnssec_v1.yaml
policies/templates/gcp_external_ip_access_v1.yaml
policies/templates/gcp_gke_dashboard_v1.yaml
policies/templates/gcp_gke_legacy_abac_v1.yaml
policies/templates/gcp_gke_restrict_pod_traffic_v1.yaml
policies/templates/gcp_glb_external_ip_access_constraint_v1.yaml
policies/templates/gcp_iam_allowed_bindings_v1.yaml
policies/templates/gcp_iam_allowed_policy_member_domains.yaml
policies/templates/gcp_iam_restrict_service_account_creation_v1.yaml
policies/templates/gcp_network_routing_v1.yaml
policies/templates/gcp_serviceusage_allowed_services_v1.yaml
policies/templates/gcp_sql_allowed_authorized_networks_v1.yaml
policies/templates/gcp_sql_public_ip_v1.yaml
policies/templates/gcp_sql_ssl_v1.yaml
policies/templates/gcp_storage_bucket_world_readable_v1.yaml
policies/templates/gcp_storage_cmek_encryption_v1.yaml
policies/templates/gcp_storage_logging_v1.yaml

So that we don't run into the following yaml parsing issue:
```
ERROR: logging before flag.Parse: I0603 15:52:13.667529  216768 validator.go:116] Unable to convert file policy-library/policies/templates/gcp_bq_dataset_location_v1.yaml, with error unmarshal []byte to yaml failed: yaml: line 86: did not find expected key, assuming this file should be skipped and continuing
```

move inline comment directive to be in the same line as the pipe

---

policies/templates/gcp_iam_allowed_bindings_v1.yaml
policies/templates/gcp_iam_allowed_policy_member_domains.yaml
validator/iam_allowed_bindings.rego
validator/iam_allowed_policy_member_domains.rego

update violation metadata to include resource name for IAM constraints GCPIAMAllowedBindingsConstraintV1 and GCPIAMAllowedPolicyMemberDomainsConstraintV1

update violation metadata to include resource name for IAM constraints

---

policies/templates/gcp_gke_allowed_node_sa_v1.yaml
policies/templates/gcp_gke_dashboard_v1.yaml
policies/templates/gcp_gke_legacy_abac_v1.yaml
policies/templates/gcp_gke_node_auto_upgrade_v1.yaml
policies/templates/gcp_gke_restrict_pod_traffic_v1.yaml
policies/templates/gcp_glb_external_ip_access_constraint_v1.yaml
policies/templates/gcp_storage_bucket_world_readable_v1.yaml

Per https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#customresourcedefinition-v1beta1-apiextensions-k8s-io, the plural name must be all lowercase.
Also rename the GKE service account scope template file (only the file name is changed, so it should still be backwards compatible)

Update plural names in templates to be all lowercase

---

Makefile

Adds the explain flag from https://github.com/open-policy-agent/opa/issues/1377 to the `make test` command.

Add --explain=notes flag for tests

---

policies/templates/gcp_enforce_labels_v1.yaml
samples/enforce_label.yaml
validator/enforce_labels.rego
validator/enforce_labels_test.rego
validator/test/fixtures/enforce_labels/assets/bigtable/data.json
validator/test/fixtures/enforce_labels/assets/buckets/data.json
validator/test/fixtures/enforce_labels/assets/cloudsql/data.json
validator/test/fixtures/enforce_labels/assets/compute/disks/data.json
validator/test/fixtures/enforce_labels/assets/compute/images/data.json
validator/test/fixtures/enforce_labels/assets/compute/instances/data.json
validator/test/fixtures/enforce_labels/assets/compute/snapshots/data.json
validator/test/fixtures/enforce_labels/assets/projects/data.json
validator/test/fixtures/enforce_labels/constraints/require_labels/data.yaml

New features:
- Adding optional parameter to provide a list of resource types to scan for.
- Adding feature to specify the pattern mandatory label's values should match (list of  label: pattern object in parameters)
Support for new resource types:
- Cloud SQL instances
- BigTable instances

enforce_label update: Adding new features + new resource types

---

CONTRIBUTING.md
policies/templates/gcp_sql_public_ip_v1.yaml
samples/sql_public_ip.yaml
validator/sql_public_ip.rego

This PR contains an update to the Cloud SQL template / rego for public IP constraints. The original logic did not cover an edge case scenario where the user can still deploy a public facing Cloud SQL instance by not declaring the ipv4_enabled setting (labeled Public Scenario 2 below). I did not increment the version naming to v2 but can if that is preferred.
Public Scenario 1:
```
settings {
tier = "db-f1-micro"
ip_configuration {
ipv4_enabled = "true" #Sets a public IPV4 address
}
```
Public Scenario 2
```
settings {
tier = "db-f1-micro"
}
```
Private Scenario
```
settings {
tier = "db-f1-micro"
ip_configuration {
ipv4_enabled = "false"
}
```
In addition, a sample constraint was added and the contribution guidelines were updated to make note of the fork requirement for clarity's sake.
-

Cloud sql updates

---

policies/templates/gcp_sql_ssl_v1.yaml
validator/sql_ssl.rego

Updated the gcp_sql_ssl_v1.yaml template file to match the updated rego from #125 
- new inline rego
- updated copyright year
- fixed `package templates.gcp.GCPSQLSSLV1` to align with the constraint naming: `package templates.gcp.GCPSQLSSLConstraintV1`
- updated `sql_ssl.rego` with new package name

gcp_sql_ssl_v1.yaml

---

policies/templates/gcp_enforce_labels_v1.yaml
validator/enforce_labels.rego
validator/enforce_labels_test.rego
validator/test/fixtures/enforce_labels/assets/bigtable/data.json
validator/test/fixtures/enforce_labels/constraints/data.yaml

CAI just released a new type for bigtable instances, clusters and table. Updating enforce label to match this change.

Updating bigtable resource type 

---

docs/user_guide.md

Addresses #164. Updated documentation for the policy library sync feature that will be released with Forseti 2.20.0. Related Terraform PR: https://github.com/forseti-security/terraform-google-forseti/pull/239
The updated user guide can be viewed here: https://github.com/gkowalski-google/policy-library/blob/feature/policy-library-sync-documentation/docs/user_guide.md

Updated user guide for the policy library sync.

---

policies/templates/gcp_gke_disable_legacy_endpoints_v1.yaml
policies/templates/gcp_sql_maintenance_window_v1.yaml
validator/gke_disable_legacy_endpoints.rego
validator/test/fixtures/gke_disable_legacy_endpoints/assets/data.json

#172 
Fix:
- The rule is currenlty inverted, it detect as non compliant the nodepooll where legacy en points are disabled
- Wired: CAI json export containts the strings "true" and "false" instead of bolean true/false ...
- The  lib.get_default call use a bolean default value while is should be a string to stay consistent with CAI strange behavior
- fixture data.json updated accordingly

Fix inverted rule

---

policies/templates/gcp_cmek_rotation_v1.yaml
policies/templates/gcp_sql_maintenance_window_v1.yaml
validator/cmek_rotation.rego
validator/cmek_rotation_test.rego
validator/test/fixtures/cmek_rotation/constraints/exemptions/data.yaml

#56 
It is not possible to delete a key ring.
Adding an exemption list enable to mute the violations once fixed
fixture update with 1 more test

add exemption list to kms

---

docs/user_guide.md

The main change here is to improve the documentation for users who want to use the Policy Library sync with Forseti (either Git or GCS). I also removed some out-dated Forseti documentation from the user guide, and added a note about using a public repository for storing the user's Policy Library.
Fixes #189 and #183.

Update User Guide for Forseti

---

policies/templates/gcp_compute_external_ip_access_v1.yaml
validator/test/fixtures/vm_external_ip/constraints/forbid_external_ip_regex_blacklist_all/data.yaml
validator/test/fixtures/vm_external_ip/constraints/forbid_external_ip_regex_whitelist_all/data.yaml
validator/vm_external_ip.rego
validator/vm_external_ip_test.rego

Adds regex based matching to external IP constraints. Now it is possible to whitelist all VMs with a naming convention such as ".*frontend.*"

adds regex functionality to vm external ip detection

---

policies/templates/gcp_enforce_naming_v1.yaml
samples/gcp_enforce_naming.yaml
validator/gcp_enforce_naming.rego
validator/gcp_enforce_naming_test.rego
validator/test/fixtures/gcp_enforce_naming/assets/data.json
validator/test/fixtures/gcp_enforce_naming/constraints/all_match/data.yaml
validator/test/fixtures/gcp_enforce_naming/constraints/partial_match/data.yaml

Enables security teams to create naming policies for the resources. For each resource, you are able to define different and multiple naming patterns

Add policy for resource naming convention

---

policies/templates/gcp_app_service_versions.yaml
policies/templates/gcp_compute_ip_forward_v1.yaml
policies/templates/gcp_enforce_labels_v1.yaml
policies/templates/gcp_gke_enable_stackdriver_kubernetes_engine_monitoring_v1.yaml
policies/templates/gcp_restricted_firewall_rules_v1.yaml
policies/templates/gcp_vpc_sc_ip_range_v1.yaml
samples/gke_enable_stackdriver_kubernetes_engine_monitoring.yaml
validator/gke_enable_stackdriver_kubernetes_engine_monitoring.rego
validator/gke_enable_stackdriver_kubernetes_engine_monitoring_test.rego
validator/test/fixtures/gke_enable_stackdriver_kubernetes_engine_monitoring/constraints/data.yaml

The constraint framework migration made FCV pickier about the input since it's actually looking at the fields.  There were some issues in the existing policy library constraint templates that this fixes.

Fix some constraint templates

---

policies/templates/gcp_restricted_firewall_rules_v1.yaml
policies/templates/gcp_vpc_sc_project_perimeter_v2.yaml
policies/templates/legacy/gcp_vpc_sc_project_perimeter_v1.yaml
samples/legacy/vpc_sc_project_perimeter_v1_whitelist.yaml
samples/restrict_fw_rules_rdp_world_open.yaml
samples/restrict_fw_rules_ssh_world_open.yaml
samples/restrict_fw_rules_world_open.yaml
samples/vpc_sc_project_perimeter_v1_blacklist.yaml
samples/vpc_sc_project_perimeter_whitelist.yaml
validator/test/fixtures/vpc_sc_project_perimeter_v2/assets/data.json
validator/test/fixtures/vpc_sc_project_perimeter_v2/constraints/blacklist/data.yaml
validator/test/fixtures/vpc_sc_project_perimeter_v2/constraints/whitelist/data.yaml
validator/vpc_sc_project_perimeter_v2.rego
validator/vpc_sc_project_perimeter_v2_test.rego

Some of the sample constraints were not conforming to the openapi
schema.  Also, two templates had errors in the openapi spec portion.

Fix openapi schema and constraints.

---

validator/bigquery_dataset_world_readable.rego
validator/bigquery_dataset_world_readable_test.rego
validator/test/fixtures/bigquery_dataset_world_readable/assets/data.json

`GCPBigQueryDatasetWorldReadableConstraintV1` checks for `allAuthenticatedUsers `, but not for `allUsers ` like `GCPStorageBucketWorldReadableConstraintV1 ` does.

Fixed GCPBigQueryDatasetWorldReadableConstraintV1

---

policies/templates/gcp_bigquery_table_retention_v1.yaml
samples/bigquery_table_retention.yaml
validator/bigquery_table_retention.rego
validator/bigquery_table_retention_test.rego
validator/test/fixtures/bigquery_table_retention/assets/data.json
validator/test/fixtures/bigquery_table_retention/constraints/max_retention_only/data.yaml
validator/test/fixtures/bigquery_table_retention/constraints/max_retention_only_one_exemption/data.yaml
validator/test/fixtures/bigquery_table_retention/constraints/min_max_retention/data.yaml
validator/test/fixtures/bigquery_table_retention/constraints/min_max_retention_one_exemption/data.yaml
validator/test/fixtures/bigquery_table_retention/constraints/min_retention_only/data.yaml
validator/test/fixtures/bigquery_table_retention/constraints/min_retention_only_one_exemption/data.yaml

BigQuery Table constraint for #271
This PR creates a BigQuery Table Retention constraint that checks for the retention policy of a BigQuery table and compares the user defined number of days the retention of a BigQuery table should be against what it actually is, utilizing the creationTime and expirationTime fields found in the BigQuery table resource.
This constraint provides the following features:
1. **minimum_retention_days**
- minimum_retention_days identifies the minimum number of days the retention of a BigQuery table should be. 
- Generate a violation if the resource retention is less than the minimum number of retention days allowed.
2. **maximum_retention_days**
- maximum_retention_days identifies the maximum number of days the retention of a BigQuery table can be.
- Generate a …

BigQuery Table Retention Constraint v1

---

cloudbuild/Dockerfile

Reverts forseti-security/policy-library#279 back to 0.16.0

Revert "Updating opa version to 0.17.2"

---

policies/templates/gcp_compute_network_interface_whitelist_v1.yaml
validator/compute_network_interface_whitelist.rego
validator/test/fixtures/compute_network_interface_whitelist/assets/data.json

Update GCP compute network interface whitelist template to use networkInterfaces and accessConfigs fields. Updated test asset data to reflect the change that will go live on March 10th. This change will also work with existin CAI exports generated after the CAI field change went live in September.
Resolves #290

Update GCP compute network interface whitelist template

---

policies/templates/gcp_gke_enable_shielded_nodes_v1.yaml
samples/gke_enable_shielded_nodes.yaml
validator/gke_enable_shielded_nodes.rego
validator/gke_enable_shielded_nodes_test.rego
validator/test/fixtures/gke_enable_shielded_nodes/assets/data.json
validator/test/fixtures/gke_enable_shielded_nodes/constraints/enable_shielded_nodes/data.yaml

The constraint enforces that GKE clusters are created with shielded nodes, and that both secure boot and integrity logging are enabled on all node pools.

Constraint for GKE Shielded Nodes

---

policies/templates/gcp_compute_disk_resource_policies_v1.yaml
samples/compute_disk_resource_policies.yaml
validator/compute_disk_resource_policies.rego
validator/compute_disk_resource_policies_test.rego
validator/test/fixtures/compute_disk_resource_policies/assets/disks/data.json
validator/test/fixtures/compute_disk_resource_policies/assets/instances/data.json
validator/test/fixtures/compute_disk_resource_policies/constraints/allowlist_all/data.yaml
validator/test/fixtures/compute_disk_resource_policies/constraints/allowlist_none/data.yaml
validator/test/fixtures/compute_disk_resource_policies/constraints/allowlist_one/data.yaml
validator/test/fixtures/compute_disk_resource_policies/constraints/allowlist_one_exemption/data.yaml
validator/test/fixtures/compute_disk_resource_policies/constraints/denylist_all/data.yaml
validator/test/fixtures/compute_disk_resource_policies/constraints/denylist_none/data.yaml
validator/test/fixtures/compute_disk_resource_policies/constraints/denylist_one/data.yaml
validator/test/fixtures/compute_disk_resource_policies/constraints/resource_policies_default/data.yaml

Adding a policy to check for disk `resourcePolicies` (eg. snapshot schedules). Supports both `Disk` and `RegionDisk`. Also supports an empty policy ("").

Added policy for Compute Engine disk resource policies.

---

validator/bigquery_dataset_world_readable.rego
validator/bigquery_dataset_world_readable_test.rego

My changes to GCPBigQueryDatasetWorldReadableConstraintV1 introduced a bug considering every dataset as violation. Should be fixed now.

Fixed bug introduced in PR #261

---

docs/constraint_template_authoring.md
policies/templates/gcp_iam_allowed_policy_member_domains.yaml

Plural isn't used, remove it from a template as well as the docs.

Remove plural field.

---

policies/templates/gcp_gke_restrict_client_auth_methods_v1.yaml
validator/gke_restrict_client_auth_methods.rego
validator/gke_restrict_client_auth_methods_test.rego
validator/test/fixtures/gke_restrict_client_auth_methods/assets/data.json

The CAI output from recent GKE clusters doesn't show the master_auth
block. I modified the constraint to only raise an error for master_auth
blocks for GKE versions < 1.12.

Bug fix in GKE Restrict Master Auth Constraint.

---

policies/templates/gcp_gke_enable_workload_identity_v1.yaml
samples/gke_enable_workload_identity.yaml
validator/gke_enable_workload_identity.rego
validator/gke_enable_workload_identity_test.rego
validator/test/fixtures/gke_enable_workload_identity/assets/data.json
validator/test/fixtures/gke_enable_workload_identity/constraints/enable_gke_workload_identity/data.yaml

The constraint checks that workload identity is enabled on the cluster. I include both the v1 version of the configuration, which appears in CAI, and the beta version, which appears in Terraform validator when the beta provider is used.

GKE Workload Identity constraint.

---

policies/templates/gcp_sql_instance_type_v1.yaml

Setting the default value in the OpenAPI spec is not allowed by the Constraint
Framework as it has no actual effect on the rego that is executed and could be
a source of confusion if the two go out of sync.
Fixes: #306

Fix template.

---

samples/iam_restrict_gmail_bigquery_dataset.yaml
samples/iam_restrict_googlegroups_bigquery_dataset.yaml
validator/iam_allowed_bindings_test.rego
validator/test/fixtures/iam_allowed_bindings/assets/data.json
validator/test/fixtures/iam_allowed_bindings/constraints/iam_allowed_bindings_blacklist_gmail_bigquery_dataset/data.yaml
validator/test/fixtures/iam_allowed_bindings/constraints/iam_allowed_bindings_blacklist_googlegroups_bigquery_dataset/data.yaml

Add samples restricting access to BQ datasets for gmail.com and googlegroups.com email addresses. Add unit tests for these samples, and update existing unit tests for this template to new format.
Resolves #314

Add IAM sample for restricting access to BQ datasets

---

samples/restrict_fw_rules_world_open_tcp_udp_all_ports.yaml

Add sample to check for world open fw rule for tcp/udp with no ports specified.
Resolves #316

Add firewall sample for Forseti bundle

---

policies/templates/gcp_iam_allowed_bindings_v1.yaml
samples/iam_restrict_googlegroups_bigquery_dataset.yaml
validator/iam_allowed_bindings.rego
validator/iam_allowed_bindings_test.rego
validator/test/fixtures/iam_allowed_bindings/assets/data.json
validator/test/fixtures/iam_allowed_bindings/constraints/iam_allowed_bindings_blacklist_asset_names/data.yaml
validator/test/fixtures/iam_allowed_bindings/constraints/iam_allowed_bindings_whitelist_asset_names/data.yaml

Resolves #330 
Add in assetNames parameter to [IAM Allowed Bindings Constraint](https://github.com/forseti-security/policy-library/blob/master/policies/templates/gcp_iam_allowed_bindings_v1.yaml) in order to target specific assets vs. project/folder/organization wide.
This is an optional parameter- default will be [], so no version upgrade is required.
Also included in this PR:
- Tests
- Updated samples

Add in assetNames parameter to IAM Allowed Bindings Constraint

---

policies/templates/gcp_iam_custom_role_permissions_v1.yaml
samples/iam_custom_role_permissions.yaml
validator/iam_custom_role_permissions.rego
validator/iam_custom_role_permissions_test.rego
validator/test/fixtures/iam_custom_role_permissions/assets/data.json
validator/test/fixtures/iam_custom_role_permissions/constraints/iam_custom_role_permissions_allowlist/data.yaml
validator/test/fixtures/iam_custom_role_permissions/constraints/iam_custom_role_permissions_allowlist_all/data.yaml
validator/test/fixtures/iam_custom_role_permissions/constraints/iam_custom_role_permissions_denylist/data.yaml
validator/test/fixtures/iam_custom_role_permissions/constraints/iam_custom_role_permissions_denylist_all/data.yaml
validator/test/fixtures/iam_custom_role_permissions/constraints/iam_custom_role_permissions_no_title/data.yaml
validator/test/fixtures/iam_custom_role_permissions/constraints/iam_custom_role_permissions_title_caps/data.yaml
validator/test/fixtures/iam_custom_role_permissions/constraints/iam_custom_role_permissions_wrong_title/data.yaml
validator/test_utils.rego

This PR creates an IAM Policy Custom Role Permissions constraint that checks whether the user defined permissions are either allowed or denied in a user defined custom role.
A sample playground for this constraint is provided [here](https://play.openpolicyagent.org/p/U4DDvP39H1).
1. **mode**
- Enforcement mode, [denylist, allowlist] , defaults to allowlist.
2. **title**
- The custom role title to scan for, found on the IAM Roles page.
- E.g. 'My Custom Role for BigQuery'
3. **permissions**
- Permissions to either allow or deny for the given custom role, depending on mode; Wildcards (*) supported.
- E.g. 'bigquery.datasets.*' will search for any permissions that start with bigquery.datasets, such as bigquery.datasets.get
- E.g. 'bigquery.**' will search for any permissions that start with …

IAM Custom Role Permissions Constraint V1

---

policies/templates/gcp_iam_required_bindings_v1.yaml
validator/iam_required_bindings.rego
validator/iam_required_bindings_test.rego
validator/test/fixtures/iam_required_bindings/assets/data.json
validator/test/fixtures/iam_required_bindings/constraints/iam_required_bindings_project_asset_name/data.yaml

Related to #330 
Add in assetNames parameter to [IAM Required Bindings Constraint](https://github.com/forseti-security/policy-library/blob/master/policies/templates/gcp_iam_required_bindings_v1.yaml) in order to target specific assets vs. project/folder/organization wide.
This is an optional parameter- default will be [], so no version upgrade is required.
Also included in this PR:
- Tests

Add in assetNames parameter to IAM Required Bindings Constraint

---

scripts/cft.sh

I was getting mix of number and UUID IDs in my case. This is an example output of `asset export` command:
```
Export in progress for root asset [organizations/<ORG_ID>].
Step #0: Use [gcloud asset operations describe organizations/<ORG_ID>/operations/ExportAssets/IAM_POLICY/5eb459b4-0000-2057-ad4a-883d24f377b8] to check the status of the operation.
```
According to the doco it could be UUID as well: https://cloud.google.com/asset-inventory/docs/exporting-to-cloud-storage#exporting_an_asset_snapshot

Support UUID in export operations

---

policies/templates/gcp_gke_enable_alias_ip_ranges.yaml
validator/gke_enable_alias_ip_ranges.rego
validator/gke_enable_alias_ip_ranges_test.rego
validator/test/fixtures/gke_enable_alias_ip_ranges/assets/data.json

The field use_ip_alias has been removed from the google provider. This causes the constraint to fail on clusters that have ip alias enabled.
According to the changelog, the new indication of a route-based cluster is the missing ip_allocation policy block. I updated the constraint to use the new system.
https://www.terraform.io/docs/providers/google/guides/version_3_upgrade.html#ip_allocation_policy-will-catch-out-of-band-changes-use_ip_aliases-removed

Support for ip_alias constraint with 3.0+ google providers.

---

policies/templates/gcp_iam_audit_log.yaml
validator/iam_audit_log_test.rego
validator/test/fixtures/iam_audit_log/assets/data.json

The name of the resource in the `data.json` is `//cloudresourcemanager.googleapis.com/ignore-asset-type`

minor fix in iam audit log tests

---

README.md

Current instruction to create Forseti bundle 
```
export BUNDLE=forseti-security
kpt pkg get https://github.com/forseti-security/policy-library.git ./policy-library
kpt fn source policy-library/samples/ | \
kpt fn run --image gcr.io/config-validator/get-policy-bundle:latest -- bundle=bundles.validator.forsetisecurity.org/$BUNDLE | \
kpt fn sink policy-library/policies/constraints/
```
fails with error:
```
Error: bundle does not exist: bundles.validator.forsetisecurity.org/bundles.validator.forsetisecurity.org/forseti-security.
at /home/node/app/dist/get_policy_bundle.js:39:19
at Generator.next (<anonymous>)
at /home/node/app/dist/get_policy_bundle.js:23:71
at new Promise (<anonymous>)
at __awaiter (/home/node/app/dist/get_policy_bundle.js:19:12)
at getPolicyBundle …
```

fix kpt bundle param

---

policies/templates/gcp_storage_bucket_policy_only_v1.yaml
validator/storage_bucket_policy_only.rego
validator/storage_bucket_policy_only_test.rego
validator/test/fixtures/storage_bucket_policy_only/assets/data.json

This pull requests updates `validator/storage_bucket_policy_only.rego` and derived/related files to consider the `uniformBucketLevelAccess` property in addition of the deprecated `bucketPolicyOnly`.
Closes #388

Add check for uniform bucket access level

---

docs/user_guide.md

The command in the sample Cloud Shell is incorrect and I fixed it.
This [Cloud Shell's](https://console.cloud.google.com/cloudshell/open?cloudshell_image=gcr.io/graphite-cloud-shell-images/terraform:latest&cloudshell_git_repo=https://github.com/forseti-security/policy-library.git) current path is already in the policy-library repository.
```
$ pwd
/home/yuto_komai/cloudshell_open/policy-library
$ 
$ cp policy-library/samples/iam_service_accounts_only.yaml policy-library/policies/constraints
cp: cannot stat 'policy-library/samples/iam_service_accounts_only.yaml': No such file or directory
```
if fixed it
```
$ cp samples/iam_service_accounts_only.yaml policies/constraints 
$ 
$ ls -la policies/constraints
total 20
drwxr-xr-x 2 yuto_komai yuto_komai 4096 Feb 10 06:59 .
drwxr-xr-x 4 …
```

fix user_guide sample command

---

docs/user_guide.md

As of Terraform 0.12, we can't read plan files directly, only JSON representations that are generated in a separate step.
Support for Terraform 0.11 was dropped from terraform-validator last December in https://github.com/GoogleCloudPlatform/terraform-validator/pull/160.

Updated terraform validator usage to reflect requiring a .json file.

---

Makefile
cloudbuild.yaml

Replace rego v0.17.0 tests with v0.24.0. 
Lines up with https://github.com/forseti-security/config-validator/pull/162

Opa v0.24.0

---

docs/user_guide.md

Terraform Validator is now using semver release versions. This change updates the docs to reflect that change, and to direct users to use the semver releases.

Updated docs to reflect TFV semver releases

---

policies/templates/gcp_iam_restrict_service_account_key_age_v1.yaml
validator/gcp_iam_restrict_service_account_key_age.rego
validator/gcp_iam_restrict_service_account_key_age_test.rego
validator/test/fixtures/gcp_iam_restrict_service_account_key_age/assets/data.json

Adds a workaround for https://github.com/open-policy-agent/opa/issues/4098

fix: Handle expiration dates in the far future 

---

policies/templates/gcp_gke_enable_binauthz_v1.yaml
samples/gke_enable_binauthz.yaml
validator/gke_enable_binauthz.rego
validator/gke_enable_binauthz_test.rego
validator/test/fixtures/gke_enable_binauthz/assets/data.json
validator/test/fixtures/gke_enable_binauthz/constraints/gke_enable_binauthz/data.yaml

Fixes #419 
- Copied `gcp_gke_enable_binauthz_v1` template without `ancestry_path`
- Copied sample `gke_enable_binauthz` constraint
- Copied source Rego without `ancestry_path` and test Rego
- Copied fixture test data and test constraint

Add gke_enable_binauthz policy to master

---

bundler/dist/generate_docs.js

This was missed in the last commit and most likely the reason why the build is failing.

fix:adds the doc-gen fix to the JS file in dist/

---

policies/templates/gcp_network_enable_flow_logs_v1.yaml
validator/network_enable_flow_logs.rego
validator/network_enable_flow_logs_test.rego
validator/test/fixtures/network_enable_flow_logs/assets/data.json

FIxes #414 
This PR main idea is to consider both versions (old and new) of Flow Logs parameters on the Subnetwork definition:
- Old version - before google provider 3.0: enable_flow_logs
- New version - after google provider 3.0: log_config
If both of them are false, the validation fails.
Some test data were added and tested on it's data test file validator/test/fixtures/network_enable_flow_logs/assets/data.json
**Manual tests:**
We tried to test it manually with a subnetwork resource definition using both versions of google provider (one where it uses the old field and one that uses the new field) but we faced a problem with the old version. 
When we used the validation with `gcloud beta terraform vet` and also `terraform validator` , apparently during the process to convert the Plan …

fix: update constraint for vpc flow logs to check on new field

---

samples/compute_block_ssh_keys.yaml

The old syntax is failing validator with MAP errors, YAML syntax was updated to fix the gcloud error. The fix was tested and working as intended.
For Reference, Error with previous Code
```
Validating resources...done.                                                                                                                              
ERROR: gcloud crashed (KeyError): 'map'
If you would like to report this issue, please run the following command:
gcloud feedback
To check gcloud for common problems, please run the following command:
gcloud info --run-diagnostics
```

YAML Syntax Fix for compute_block_ssh_keys policy
