GoogleCloudPlatform/policy-library

validator/test/fixtures/constraints/forbid_external_ip_blacklist/data.yaml, validator/test/fixtures/constraints/forbid_external_ip_blacklist_all/data.yaml, validator/test/fixtures/constraints/forbid_external_ip_default/data.yaml, validator/test/fixtures/constraints/forbid_external_ip_whitelist_all/data.yaml, validator/test/fixtures/constraints/iam_allowed_policy_member_all_domains/data.yaml, validator/test/fixtures/constraints/iam_allowed_policy_member_two_domains/data.yaml
=> Update test constraint fixture targets

policies/templates/gcp_external_ip_access.yaml, policies/templates/gcp_network_routing.yaml, validator/network_routing.rego, validator/test/fixtures/assets/compute_instances/data.json, validator/test/fixtures/assets/networks/data.json, validator/vm_external_ip.rego
=> Updated resource type to reference to CAI GA resource type.

docs/user_guide.md
=> Update user guide

docs/cai.md
v1beta1 uses different, deprecated asset types
=> Update CAI endpoint to v1

policies/templates/gcp_dnssec_v1.yaml, policies/templates/gcp_gke_dashboard_v1.yaml
=> Format constraint templates.

policies/constraints/README.md, policies/templates/legacy/README.md
"policies/templates/legacy" is meant to contain legacy template files; also add a README.md there to mention it.
Delete the .gitkeep file under "policies/constraints" and replace it with a README file.
=> Add a "legacy" directory under "templates"

samples/storage_blacklist_public.yaml, samples/storage_logging.yaml
add samples for GCPStorageBucketWorldReadableConstraintV1 and GCPStorageLoggingConstraintV1 kind.
=> add samples for GCPStorageBucketWorldReadableConstraintV1 and GCPStorageLoggingConstraintV1 kind

policies/templates/gcp_sql_location_v1.yaml, samples/sql_location.yaml, validator/sql_location.rego, validator/sql_location_test.rego, validator/test/fixtures/sql_location/assets/sql_instances/data.json, validator/test/fixtures/sql_location/constraints/allowlist_all/data.yaml, validator/test/fixtures/sql_location/constraints/allowlist_none/data.yaml, validator/test/fixtures/sql_location/constraints/allowlist_one/data.yaml, validator/test/fixtures/sql_location/constraints/allowlist_one_exemption/data.yaml, validator/test/fixtures/sql_location/constraints/denylist_all/data.yaml, validator/test/fixtures/sql_location/constraints/denylist_none/data.yaml, validator/test/fixtures/sql_location/constraints/denylist_one/data.yaml, validator/test/fixtures/sql_location/constraints/denylist_one_exemption/data.yaml, validator/test/fixtures/sql_location/constraints/location_default/data.yaml
Constraint to check Cloud SQL instance region
=> Added constraint & template for Cloud SQL location

samples/iam_restrict_role.yaml
=> Update description for iam_restrict_role.yaml

validator/sql_ssl.rego, validator/sql_ssl_test.rego, validator/test/fixtures/sql_ssl/assets/data.json
=> Fix CAI data format for require_ssl constraint

validator/sql_ssl.rego, validator/sql_ssl_test.rego
Fix regression caused by #127.
=> Fix package for sql ssl test

Makefile, cloudbuild.yaml, cloudbuild/Dockerfile
Updating builder image to include python3 and pip3 (+yaml module)
Adding target to the Makefile to check if make fmt would change any file in lib/ validator/ 
Adding steps to the cloudbuild file to run make check_samples and make test_format
=> Updating cloud build integration

Makefile, README.md, docs/user_guide.md, scripts/cft.sh
Integrates policy-library with CFT scorecard to run add ability to run audit on real CAI data (existing Forseti bucket or new bucket + dump)
=> Add CFT scorecard integration

Makefile
As suggested [here](https://github.com/forseti-security/policy-library/pull/178#issuecomment-544980605).
=> Increase test timeout

samples/gke_enable_stackdriver_logging.yaml, samples/gke_enable_stackdriver_monitoring.yaml
Adjusting CIS annotation to CIS 1.0
=> Update CIS annotation to CIS 1.0

samples/gke_dashboard_disable.yaml, samples/gke_enable_stackdriver_logging.yaml, samples/gke_enable_stackdriver_monitoring.yaml, samples/gke_legacy_abac.yaml, samples/gke_master_authorized_networks_enabled.yaml, samples/gke_node_pool_auto_upgrade.yaml
Updating annotations for CIS and GKE Hardening Guide
=> More updates on CIS / GKE Hardening annotations

policies/templates/gcp_allowed_resource_types_v1.yaml, policies/templates/gcp_always_violates_v1.yaml, policies/templates/gcp_appengine_location_v1.yaml, policies/templates/gcp_dataproc_location_v1.yaml, policies/templates/gcp_enforce_labels_v1.yaml, policies/templates/gcp_restricted_firewall_rules_v1.yaml, policies/templates/gcp_spanner_location_v1.yaml, validator/allowed_resource_types.rego, validator/appengine_location.rego, validator/dataproc_location.rego, validator/enforce_labels.rego, validator/restricted_firewall_rules.rego, validator/spanner_location.rego
Rego format fixes with opa version upgraded from v0.13.2 to v0.16.0
This PR will now fail the Cloud Build CI test but should pass after #249 is merged
=> rego format fixes with latest opa version

policies/templates/gcp_bigquery_dataset_world_readable_v1.yaml, policies/templates/gcp_iam_allow_ban_roles_v1.yaml, policies/templates/gcp_iam_allowed_bindings_v1.yaml, policies/templates/gcp_sql_instance_type_v1.yaml
This is auto-generated by `make build`.
=> Sync templates with regos.

policies/templates/gcp_gke_container_optimized_os.yaml, validator/gke_container_optimized_os.rego, validator/gke_container_optimized_os_test.rego, validator/test/fixtures/gke_container_optimized_os/assets/data.json, validator/test/fixtures/gke_container_optimized_os/constraints/gke_container_optimized_os_containerd/data.yaml
Modified the gke_container_optimized_os to support optionally specifying
COS_CONTAINERD images as allowed. COS_CONTAINERD is necessary for GKE
and gVisor.
=> Added optional support for cos_containerd.

validator/allowed_resource_types_test.rego, validator/always_violates_test.rego, validator/appengine_location_test.rego, validator/bigquery_cmek_test.rego
Use list comprehensions in tests to make them more succinct.
=> Reduce boilerplate from test fixtures

validator/allowed_resource_types_test.rego, validator/always_violates_test.rego, validator/app_service_versions_test.rego, validator/appengine_location_test.rego, validator/bigquery_cmek_test.rego, validator/bigquery_dataset_world_readable_test.rego, validator/bq_dataset_location.rego, validator/bq_dataset_location_test.rego, validator/cmek_rotation_test.rego, validator/test_utils.rego
Following up on #288, this reduces test duplication further by adding some common utility functions.
=> Add test utils

.gitignore, Makefile, README.md, cloudbuild.yaml, cloudbuild/Dockerfile
=> Add support for testing with multiple rego versions.

Makefile, scripts/check_format.sh
Adjust output to print what was wrong and resolution.
=> Improve make_format error message.

samples/bigquery_world_readable.yaml, samples/restrict_fw_rules_world_open.yaml, samples/storage_blacklist_public.yaml
=> Add forseti annotation for bigquery, firewall, and storage samples.

samples/cmek_rotation_100_days.yaml, validator/cmek_rotation_test.rego, validator/test/fixtures/cmek_rotation/assets/data.json, validator/test/fixtures/cmek_rotation/constraints/one_hundred_days/data.yaml
=> Add sample to check if cmek rotation period is greater than 100 days.

Makefile
=> Update makefile to add common dev tasks using opa docker image.

policies/templates/gcp_restricted_firewall_rules_v1.yaml, validator/restricted_firewall_rules.rego, validator/restricted_firewall_rules_test.rego, validator/test/fixtures/restricted_firewall_rules/assets/protocol_and_all_ports/data.json, validator/test/fixtures/restricted_firewall_rules/constraints/protocol_and_all_ports/data.yaml
=> Update restricted firewall rules template to support scanning for FW rules that expose all ports.

docs/user_guide.md
=> Centralized the Forseti documentation on the Forseti website

cloudbuild.yaml
Adds check for duplicate template names / kinds.
=> Update policy-tool image to latest version.

policies/templates/gcp_bigquery_dataset_world_readable_v1.yaml, policies/templates/gcp_bq_dataset_location_v1.yaml, policies/templates/gcp_compute_network_interface_whitelist_v1.yaml, policies/templates/gcp_iam_restrict_service_account_key_age_v1.yaml, policies/templates/gcp_lb_forwarding_rules_whitelist.yaml, policies/templates/gcp_sql_world_readable_v1.yaml
=> Fix: correct BigQuery world readable dataset policy

policies/templates/gcp_bq_dataset_location_v1.yaml, policies/templates/gcp_sql_location_v1.yaml, policies/templates/gcp_storage_location_v1.yaml, validator/bq_dataset_location.rego, validator/sql_location.rego, validator/storage_location.rego, validator/test/fixtures/bq_dataset_location/constraints/allowlist_one/data.yaml, validator/test/fixtures/sql_location/constraints/allowlist_one/data.yaml, validator/test/fixtures/storage_location/constraints/allowlist_one/data.yaml
Fixes https://github.com/forseti-security/policy-library/issues/369
=> fix sql, bq, storage location exemptions empty list

bundler/build/generate_docs.Dockerfile
Fixes https://github.com/forseti-security/policy-library/issues/375
=> fix: Update build image to use root

policies/templates/gcp_gke_dashboard_v1.yaml, validator/gke_dashboard.rego, validator/gke_dashboard_test.rego, validator/test/fixtures/gke_dashboard/assets/data.json
=> Fix: Change default for GKE dashboard to disabled

policies/templates/gcp_network_enable_flow_logs_v1.yaml, validator/network_enable_flow_logs.rego, validator/network_enable_flow_logs_test.rego, validator/test/fixtures/network_enable_flow_logs/assets/data.json
=> fix: add VPC Flow logs exceptions for REGIONAL_MANAGED_PROXY and INTERNAL_HTTPS_LOAD_BALANCER
